# Generated by Django 5.0.14 on 2026-09-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fplmanagerprofile_telegram_chat_id'),
        ('fpl_data', '0005_gameweek_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fplmanagerprofile',
            name='free_transfers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fplmanagerprofile',
            name='last_synced_gameweek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpl_data.gameweek'),
        ),
    ]
