# Generated by Django 5.0.14 on 2026-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fplmanagerprofile_free_transfers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fplmanagerprofile',
            name='fpl_team_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
