# Generated by Django 5.0.14 on 2026-09-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_fplmanagerprofile_fpl_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fplmanagerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'فارسی')], default='en', max_length=2),
        ),
    ]
