# Generated by Django 5.0.14 on 2026-08-20 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('deadline_time', models.DateTimeField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_next', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('average_entry_score', models.PositiveIntegerField(blank=True, null=True)),
                ('highest_score', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('strength', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('web_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GKP', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('price', models.DecimalField(decimal_places=1, max_digits=4)),
                ('form', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_points', models.IntegerField(default=0)),
                ('selected_by_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('status', models.CharField(default='a', max_length=1)),
                ('chance_of_playing_next_round', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fpl_data.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameweekStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('goals_scored', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('clean_sheets', models.PositiveSmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='fpl_data.gameweek')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_stats', to='fpl_data.player')),
            ],
            options={
                'unique_together': {('player', 'gameweek')},
            },
        ),
    ]
