# Generated by Django 5.0.14 on 2026-08-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='strength',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
