# Generated by Django 5.0.14 on 2026-08-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0002_alter_team_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='strength',
        ),
        migrations.AddField(
            model_name='player',
            name='expected_assists',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='expected_goal_involvements',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='expected_goals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='ict_index',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='news',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='bps',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='expected_assists',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='expected_goal_involvements',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='expected_goals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='ict_index',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_attack_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_attack_home',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_defence_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_defence_home',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_overall_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_overall_home',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.PositiveIntegerField(unique=True)),
                ('difficulty_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kickoff_time', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('gameweek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='fpl_data.gameweek')),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fpl_data.team')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fpl_data.team')),
            ],
        ),
    ]
