# Generated by Django 5.0.14 on 2026-09-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0003_remove_team_strength_player_expected_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clearances_blocks_interceptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='defensive_contribution',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='defensive_contribution_per_90',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='expected_goals_conceded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='recoveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tackles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='clearances_blocks_interceptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='defensive_contribution',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='recoveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergameweekstat',
            name='tackles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
