# Generated by Django 5.0.14 on 2026-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0004_player_clearances_blocks_interceptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
