# Generated by Django 5.0.14 on 2026-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0005_gameweek_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameweekstat',
            name='expected_goals_conceded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
